version: '3.9'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Expose to localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pulsebord
      MONGO_INITDB_DATABASE: datatodashboard
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
